services:
  # Serviço do PostgreSQL
  db:
    image: postgres
    container_name: banco
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  # Serviço do Spring
  api:
    build: ./backend
    container_name: spring
    volumes:
      - ./backend:/app
      - /app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true

  # # Serviço do Angular
  web:
    build: ./frontend
    container_name: angular
    volumes:
      - ./frontend:/home/node/task
      - /home/node/task/node_modules # Isso é um volume ANÔNIMO, serve para não sobrescrever a pasta quando tiver um volume mapeado.
    ports:
      - "4200:4200"
    depends_on:
      - api
    